image: Visual Studio 2017

configuration:
  - Debug
  
clone_folder: c:\projects\sc

platform:
- x86
- x64     

install:
  - mkdir C:\projects\deps
  - cd C:\projects\deps
  - ps: >-
    $cmakeUninstallPath = "${env:ProgramFiles(x86)}\CMake\Uninstall.exe"
    if([IO.File]::Exists($cmakeUninstallPath)) {
        Write-Host "Uninstalling previous CMake ..." -ForegroundColor Cyan
        # uninstall existent
        "`"$cmakeUninstallPath`" /S" | out-file ".\uninstall-cmake.cmd" -Encoding ASCII
        & .\uninstall-cmake.cmd
        del .\uninstall-cmake.cmd
        Start-Sleep -s 10
    }
  - set CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-rc3-win64-x64.msi"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake-3.8.0-rc3-win64-x64.msi
  - start /wait msiexec /i C:\projects\deps\cmake-3.8.0-rc3-win64-x64.msi /quiet /qn /norestart
  - cmake --version
  - echo Running cmake...
  - cd c:\projects\sc
  - mkdir build
  - cd build
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - powershell -exec bypass scripts\bootstrap.ps1  
  - .\vcpkg install openssl
  - cd ..
  - cmake -G "Visual Studio 15 2017" -DCMAKE_TOOLCHAIN_FILE=c:/projects/sc/build/vcpkg/scripts/buildsystems/vcpkg.cmake ..

build_script:
  - cmake --build .
