image: Visual Studio 2017

configuration:
  - Debug
  
clone_folder: c:\projects\sc

platform:
- x86
- x64     

install:
  - echo %PATH%
  - cd "C:\Program Files (x86)"
  - rd /s /q CMake
  - mkdir CMake
  - cd c:\projects\sc
  - set CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-rc3-win32-x86.zip"		
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip		
  - 7z x cmake.zip -o"C:\Program Files (x86)\CMake" > nul
  - cmake --version
  - echo Running cmake...
  - mkdir build
  - cd build
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - powershell -exec bypass scripts\bootstrap.ps1  
  - .\vcpkg install openssl
  - cd ..
  - cmake -G "Visual Studio 15 2017" -DCMAKE_TOOLCHAIN_FILE=c:/projects/sc/build/vcpkg/scripts/buildsystems/vcpkg.cmake ..

build_script:
  - cmake --build .
