
clone_folder: c:\projects\sc

platform:
- x86
- x64

environment:
  matrix:
  - GENERATOR: "Visual Studio 15 2017"
    CONFIG: Debug
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

  - GENERATOR: "Visual Studio 15 2017"
    CONFIG: Release
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    
install:
  - ps: If ($env:Platform -Match "x86"){ $env:CMAKE_ARCH="" } Else { $env:CMAKE_ARCH=" Win64"}
  - cd c:\projects\sc
  - mkdir build
  - cd build

build_script:
  - cmd: cmake .. -G"%GENERATOR%" -DBUILD_SHARED_LIBS=OFF 
  - cmd: cmake --build . --config %CONFIG%
  - 7z a %APPVEYOR_REPO_TAG_NAME%_vc140_%CONFIGURATION%_%PLATFORM%_MT.zip -i!%APPVEYOR_BUILD_FOLDER%\build\%CONFIGURATION%\*.lib
  - 7z a -tzip %APPVEYOR_REPO_TAG_NAME%_vc140_%CONFIGURATION%_%PLATFORM%_MT.zip -i!%APPVEYOR_BUILD_FOLDER%\include\ScreenCapture.h
  - appveyor PushArtifact %APPVEYOR_REPO_TAG_NAME%_vc140_%CONFIGURATION%_%PLATFORM%_MT.zip
  - cmd: cmake .. -G"%GENERATOR%" -DBUILD_SHARED_LIBS=ON . 
  - cmd: cmake --build . --config %CONFIG%
  - 7z a %APPVEYOR_REPO_TAG_NAME%_vc140_%CONFIGURATION%_%PLATFORM%_MD.zip -i!%APPVEYOR_BUILD_FOLDER%\build\%CONFIGURATION%\*.dll -i!%APPVEYOR_BUILD_FOLDER%\build\%CONFIGURATION%\*.lib
  - 7z a -tzip %APPVEYOR_REPO_TAG_NAME%_vc140_%CONFIGURATION%_%PLATFORM%_MD.zip -i!%APPVEYOR_BUILD_FOLDER%\include\ScreenCapture.h
  - appveyor PushArtifact %CONFIGURATION%_%PLATFORM%_MD.zip

deploy:
  provider: GitHub
  auth_token:
    secure: WCGi6SXwa6VaPyLH6fZCrmTix+e2FA3zwzhNg8dSf3EdrcecGIR3Z0qG/vssOdfA 
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true 
