image: Visual Studio 2017

platform:
- Visual Studio 15 2017
- Visual Studio 15 2017 Win64

configuration:
  - Debug
  - Release
  
environment:
  matrix:
  - SHARED: OFF
    POSTFIXNAME: MT
  - SHARED: ON
    POSTFIXNAME: MD
    
matrix:
  fast_finish: true
  
install:
  - mkdir build
  - cd build

build_script: 
  - cmd: cmake .. -G"%platform%" -DBUILD_SHARED_LIBS=%SHARED% -DCMAKE_INSTALL_PREFIX=./output
  - cmd: cmake --build . --target INSTALL --config %CONFIG%
  

deploy:
  provider: GitHub
  auth_token:
    secure: WCGi6SXwa6VaPyLH6fZCrmTix+e2FA3zwzhNg8dSf3EdrcecGIR3Z0qG/vssOdfA 
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true 
