image: Visual Studio 2017

configuration:
  - Debug
  
clone_folder: c:\projects\sc

platform:
- x86
- x64     

install:
  - mkdir C:\projects\deps
  - cd C:\projects\deps
  
before_build:
  - echo Running cmake...
  - cd c:\projects\sc
  - mkdir build
  - cd build
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg     
  - git checkout 30a8d6e
  - powershell -exec bypass scripts\bootstrap.ps1  
  - vcpkg install openssl
  - cd ..
  - cmake -G "Visual Studio 15 2017" -DCMAKE_TOOLCHAIN_FILE=c:/projects/sc/build/vcpkg/scripts/buildsystems/vcpkg.cmake ..

  
build_script:
  - cmake --build .
