
clone_folder: c:\projects\sc

platform:
- x86
- x64

environment:
  matrix:
  - GENERATOR: "Visual Studio 15 2017"
    CONFIG: Debug
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

  - GENERATOR: "Visual Studio 15 2017"
    CONFIG: Release
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  
  matrix:
  - SHARED: OFF
    POSTFIXNAME: MT
  - SHARED: ON
    POSTFIXNAME: MD
    
 matrix:
  fast_finish: true
  
install:
  - ps: If ($env:Platform -Match "x86"){ $env:CMAKE_ARCH="" } Else { $env:CMAKE_ARCH=" Win64"}
  - cd c:\projects\sc
  - mkdir build
  - cd build

build_script:
  - cmd: cmake .. -G"%GENERATOR%" -DBUILD_SHARED_LIBS=%SHARED% -DCMAKE_INSTALL_PREFIX=./output
  - cmd: cmake --build . --target INSTALL --config %CONFIG%
  

deploy:
  provider: GitHub
  auth_token:
    secure: WCGi6SXwa6VaPyLH6fZCrmTix+e2FA3zwzhNg8dSf3EdrcecGIR3Z0qG/vssOdfA 
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true 
