language : cpp

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-6 && CXX=g++-6"
    - os: linux
      env: 
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      addons: &clang5
        apt:
          packages:
            - clang-5.0
            - g++-6
            - libssl-dev
            - libx11-dev
            - libxfixes-dev 
            - libxtst-dev
          sources: 
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
      
before_install:
  - if [[ -n "$CLANG_VERSION" ]]; then export CXX=clang++-$CLANG_VERSION CC=clang-$CLANG_VERSION; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update && brew upgrade cmake || brew install cmake;
    fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      mkdir $HOME/usr
      export PATH="$HOME/usr/bin:$PATH"
      wget https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.sh
      chmod +x cmake-3.8.2-Linux-x86_64.sh
      ./cmake-3.8.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
    fi

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        cmake . && make;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
       cmake -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_C_COMPILER="$CC" . && make;
    fi  
