language : cpp

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-6 && CXX=g++-6"
    - os: linux
      env: 
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      addons:
        apt:
          packages:
            - clang-5.0
            - libssl-dev
            - libx11-dev
            - libxfixes-dev 
            - libxtst-dev
          sources: 
            - llvm-toolchain-trusty
      
before_install:
  - if [[ -n "$CLANG_VERSION" ]]; then export CXX=clang++-$CLANG_VERSION CC=clang-$CLANG_VERSION; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update && brew upgrade cmake || brew install cmake;
    fi
    
install:    
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"
 
  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      if [[ -z "$(ls -A ${DEPS_DIR}/cmake/bin)" ]]; then
        CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz"
        mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
      fi
      export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
    fi
  - cd ..    
  
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        cmake . && make;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
       cmake -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_C_COMPILER="$CC" . && make;
    fi  
