language : cpp
    
matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-6 && CXX=g++-6"
    - os: linux
      env: 
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      addons: &clang5
        apt:
          packages:
            - clang-5.0
            - g++-6
            - libssl-dev
            - libx11-dev
            - libxfixes-dev 
            - libxtst-dev
          sources: 
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
      
before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
     CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz"
      mkdir -p ${TRAVIS_BUILD_DIR}/deps/cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C ${TRAVIS_BUILD_DIR}/deps/cmake
      export PATH="${TRAVIS_BUILD_DIR}/deps/cmake/bin:${PATH}"
    else
      brew update && brew upgrade cmake || brew install cmake;
    fi

script:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
       cmake -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_C_COMPILER="$CC" . && make;
    else
       cmake . && make;
    fi  
